- name: Ensure wget is installed
  become: true
  ansible.builtin.apt:
    name: wget
    state: present
    update_cache: yes

- name: Create keyrings directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add GitHub CLI's official GPG key
  become: true
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'

- name: Create sources.list.d directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list.d
    state: directory
    mode: '0755'

- name: Add GitHub CLI repository to Apt sources
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    state: present
    filename: github-cli
    update_cache: no

- name: Install GitHub CLI
  become: true
  ansible.builtin.apt:
    name: gh
    state: present
    update_cache: yes