- name: Install pyenv tool
  ansible.builtin.shell: >
    curl -fsSL https://pyenv.run | bash

- name: Install common dependencies for Python compilation
  become: true
  ansible.builtin.apt:
    name: [ "build-essential", "libssl-dev", "zlib1g-dev", "libbz2-dev", "libreadline-dev", "libsqlite3-dev", "wget", "curl", "llvm", "libncursesw5-dev", "xz-utils", "tk-dev", "libxml2-dev", "libxmlsec1-dev", "libffi-dev" , "liblzma-dev" ]
 